// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"ai-sdk-integration.mdx": () => import("../content/docs/ai-sdk-integration.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "introduction.mdx": () => import("../content/docs/introduction.mdx?collection=docs"), "manifests.mdx": () => import("../content/docs/manifests.mdx?collection=docs"), "registry.mdx": () => import("../content/docs/registry.mdx?collection=docs"), "architecture/agent-routing.mdx": () => import("../content/docs/architecture/agent-routing.mdx?collection=docs"), "architecture/security.mdx": () => import("../content/docs/architecture/security.mdx?collection=docs"), "architecture/system-flow.mdx": () => import("../content/docs/architecture/system-flow.mdx?collection=docs"), "components/confirmation-card.mdx": () => import("../content/docs/components/confirmation-card.mdx?collection=docs"), "components/data-browser.mdx": () => import("../content/docs/components/data-browser.mdx?collection=docs"), "components/form-card.mdx": () => import("../content/docs/components/form-card.mdx?collection=docs"), "components/metric-card.mdx": () => import("../content/docs/components/metric-card.mdx?collection=docs"), "components/suggested-actions.mdx": () => import("../content/docs/components/suggested-actions.mdx?collection=docs"), "data-sources/actions-and-invalidation.mdx": () => import("../content/docs/data-sources/actions-and-invalidation.mdx?collection=docs"), "data-sources/firebase.mdx": () => import("../content/docs/data-sources/firebase.mdx?collection=docs"), "data-sources/multiple-data-sources.mdx": () => import("../content/docs/data-sources/multiple-data-sources.mdx?collection=docs"), "data-sources/overview.mdx": () => import("../content/docs/data-sources/overview.mdx?collection=docs"), "data-sources/resources.mdx": () => import("../content/docs/data-sources/resources.mdx?collection=docs"), "data-sources/rest.mdx": () => import("../content/docs/data-sources/rest.mdx?collection=docs"), }),
};
export default browserCollections;